### ISSUE TITLE
Error when trying to run napalm: f-string expression part cannot include a backslash

### ISSUE THREAD

**Issue by infosec-us-team** [ConsenSysDiligence/napalm#8]
> Congratulations on the incredible tool. Well done! Thanks for sharing.

Steps to reproduce the error:

1- Install Napalm with:
```bash
pip3 install napalm-toolbox
```

2- Run `napalm` or `napalm-dev`

Output:
```python
Traceback (most recent call last):
  File "/home/-----------/.local/bin/napalm", line 5, in <module>
    from napalm.cli.base.main import cli
  File "/home/-----------/.local/lib/python3.10/site-packages/napalm/cli/base/main.py", line 8, in <module>
    from .collection import collections
  File "/home/-----------/.local/lib/python3.10/site-packages/napalm/cli/base/collection.py", line 54
    )
    ^
SyntaxError: f-string expression part cannot include a backslash
```

Python version:
```bash
> python3 --version
Python 3.10.12
```

**Comment by JoranHonig** [comment]
Napalm requires python 3.12 😅
